config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'

  # Main routes
  resources :users # ADD `, :only => [:new, :create, :index]` to this once tested to limit ability for users to input into database
  resources :beets # gets all available routes for Beets
  resources :comments # gets all available routes for Comments
  resources :likes # gets all available routes for Likes

  delete '/' => 'likes#destroy'

  post '/' => 'pages#clipboard'

  # Login feature
  get '/login' => 'session#new' # login form
  post '/login' => 'session#create' # process the login
  delete '/login' => 'session#destroy' # log out

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beet.rb
class Beet < ApplicationRecord
  belongs_to :user, :optional => true
  has_many :likes
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :beet, :optional => true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :beet, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :beets
  has_many :comments
  has_many :likes
  has_secure_password
  validates :email, :uniqueness => true, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user # checks

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current.user.present?
  end

  def check_for_admin
    redirect_to root_path unless @current_user.present? && @current_user.admin?
  end
end

app/controllers/beets_controller.rb
class BeetsController < ApplicationController

  def index
    @beets = Beet.all
  end

  def new
    @beet = Beet.new
  end

  def create
    beet = Beet.create :title => params[:beet][:title], :tags => params[:beet][:tags], :user_id => @current_user.id
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      beet.image = req["public_id"] # store the Cloudinary link in the image column
      beet.content = AsciiArt.new(Cloudinary::Utils.cloudinary_url(req["public_id"])).to_ascii_art(width: 70)
      beet.save
    end
    redirect_to root_path # show the beet detail page
  end

  def edit
    @beet = Beet.find params[:id]
  end

  def update
    beet = Beet.find params[:id]
    beet.update beet_params
    redirect_to beet # redirect back to the beet page
  end

  def show
    @beet = Beet.find params[:id]
    @user = @beet.user
    @comments = @beet.comments
    @comment_new = Comment.new
    @likes = Like.all
    @like_new = Like.new
  end

  def destroy
    beet = Beet.find params[:id]
    beet.destroy
    redirect_to root_path # redirect back to the index
  end

  def clipboard
    beet = Beet.find params[:id]
    IO.popen("pbcopy", "w") { |clipboard| clipboard.puts beet.content }
  end

  private
  def beet_params # setup of strong params
    params.require(:beet).permit(:title, :tags, :content, :image, :like_count, :comment_count, :user_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end


  def new
    @comment = Comment.new
  end

  def create
    comment = Comment.create comment_params
    redirect_to request.referrer
  end

  def destroy
    beet = params[:beet_id]
    user = params[:user_id]
    comment_id = params[:id]
    comment = Comment.where(id: comment_id, beet_id: beet, user_id: user)
    comment.destroy_all
    redirect_to request.referrer
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :beet_id, :user_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @likes = Like.all
  end

  def new
    @beets = Beet.all
    @likes = Like.all
    @like = Like.new
  end

  def create
    @likes = Like.all
    like = Like.create like_params
    beet = like.beet
    redirect_to root_path(anchor: "#{beet.id}")
  end

  def show
  end

  def destroy
    beet = params[:beet_id]
    user = params[:user_id]
    like = Like.where(beet_id: beet, user_id: user)
    like.destroy_all
    redirect_to root_path(anchor: beet)
  end

  private
  def like_params
    params.require(:like).permit(:beet_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @beets = Beet.all
    @likes = Like.all
    @comments = Comment.all
    @like_new = Like.new
  end

  def clipboard
    beet = Beet.find params[:id]
    IO.popen("pbcopy", "w") { |clipboard| clipboard.puts beet.content }
  end
  
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id # only search for user_id for efficiency-sake
      redirect_to root_path
    else
      flash[:error] = "Invalid username or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params # save user as an object before it's written to the server to check for duplicate submissions or other errors with the form
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update user_params
    redirect_to user
  end

  def show
    @user = User.find params[:id]
    @beets = Beet.all
    @likes = Like.all
    @like_new = Like.new
    @comments = Comment.all
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :bio, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beets_helper.rb
module BeetsHelper
end

app/helpers/commenrs_helper.rb
module CommenrsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beets/_form.html.erb
<%= form_for(@beet, :html => {:multipart => true}) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :tags %>
  <%= f.text_field :tags %>
  <%= f.label "Image to convert" %>
  <%= f.cl_image_upload :image, :class => "custom-file-input", :required => true %>
  <%= f.submit %>
<% end %>

app/views/beets/edit.html.erb
<h1>Edit your Beet!</h1>

<%= render :partial => 'form' %>

app/views/beets/index.html.erb
<h1>All Beets</h1>

<% @beets.each do |beet| %>
  <p><%= link_to cl_image_tag(beet.image, :alt => beet.user.email), beet %></p>
<% end %>

app/views/beets/new.html.erb
<div class="page-container">

  <h1>Create a Beet!</h1>

  <%= render :partial => 'form' %>

</div>

app/views/beets/show.html.erb
<h1><%= @beet.title %></h1>

<% if @current_user.present? %>

  <% if @current_user.id == @user.id || @current_user.admin? %>

    <div class="controls">
      <%= link_to 'edit post', edit_beet_path(@beet) %>
      <%= link_to 'delete beet', @beet, :method => 'delete' %>
    </div>

  <% end %>

<% end %>

<div class="post">

  <pre><%= @beet.content %></pre>

  <div class="info">

    <a href="/users/<%= @beet.user_id %>" class="info-item"><%= @beet.user.username %></a>

    <% if @current_user.present? %>

      <% if @likes.where(user_id: @current_user.id, beet_id: @beet.id).any? == true %>

        <%= link_to "♥ #{ @likes.where(beet_id: @beet.id).count }", root_path(:user_id => @current_user.id, :beet_id => @beet.id), :id => "liked", :method => 'delete' %>

      <% else %>

        <p>
          <%= form_for @like_new do |f| %>
            <%= f.hidden_field :beet_id, value: @beet.id %>
            <%= f.hidden_field :user_id, value: @current_user.id %>
            <%= f.submit "♡ #{@likes.where(beet_id: @beet.id).count}", :id => "like" %>
          <% end %>
        </p>

      <% end %>

    <% else %>

      <%= link_to "♡ #{@likes.where(beet_id: @beet.id).count}", login_path, :id => "like" %>

    <% end %>

    <div class="tooltip">
      <%= link_to "", root_path(:id => @beet.id), :class => 'far fa-copy', :id => 'clipboard', :method => 'clipboard' %><span class="tooltiptext">Copy to clipboard</span>
    </div>

  </div>

</div>

<h2>Comments <%= "[#{ @comments.where(beet_id: @beet.id).count }]" %></h2>

<% @comments.each do |comment| %>
  <div class="comments" id="<%= comment.id %>">
    <p><%= comment.content %></p>
    <div class="comments-info">
      <a href="/users/<%= comment.user.id %>"><%= comment.user.username %></a>
      <% if @current_user.present? && @current_user.id == comment.user.id %>
        <%= link_to 'delete comment', comment_path(:id => comment.id, :user_id => @current_user.id, :beet_id => @beet.id), :class => 'delete-comment', :method => 'delete' %>
      <% end %>
    </div>
  </div>
<% end %>

<% if @current_user.present? %>
  <div class="leave-comment">
    <h3>Comment on <%= @beet.user.username %>'s beet:</h3>
    <%= form_for @comment_new do |f| %>
      <%= f.text_field :content %>
      <%= f.hidden_field :beet_id, value: @beet.id %>
      <%= f.hidden_field :user_id, value: @current_user.id %>
      <%= f.submit "leave comment" %>
    <% end %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>bASCIIart (o˘◡˘o)</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= cloudinary_js_config %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">

    <%= favicon_link_tag asset_path('favicon.png') %>

    <meta property="og:title" content="bASCIIart (o˘◡˘o)" />
    <meta property="og:description" content="Create your own ASCII art by uploading an image and watch it come to life in ASCII!" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://basciiart.herokuapp.com/" />
    <%= tag :meta, property: 'og:image', content: image_url('basciiart-cover.png') %>

  </head>

  <body>

    <nav>

      <ul>

        <li><%= link_to 'bASCIIart', root_path, :class => 'title' %></li>
        <li><%= link_to 'feed', root_path, :class => 'nav-item' %></li>
        <% if @current_user.present? %>
          <li><a href="/users/<%= @current_user.id %>"><%= "view profile" %></a></li>
          <% if @current_user.admin? %>
            <li><%= link_to 'users (admin only)', users_path %></li>
          <% end %>
          <li><%= link_to "log out", login_path, :class => 'nav-item', :method => 'delete' %></li>
          <li><%= link_to "create beet!", new_beet_path, :class => 'create-beet' %></li>
        <% else %>
          <li><%= link_to 'sign up', new_user_path %></li>
          <li><%= link_to 'login', login_path %></li>
          <li><%= link_to "create beet!", login_path, :class => 'create-beet' %></li>
        <% end %>

      </ul>

    </nav>

    <div class="main-container">

      <%= yield %>

    </div>

    <div class="credits">brought to you in <%= Date.current.year %> by <a href="https://github.com/oisa/basciiart" target="_blank">oisa</a>. made possible with <a href="https://github.com/nodanaonlyzuul/asciiart" target="_blank">asciiart</a> and <a href="https://generalassemb.ly/" target="_blank">ga</a>.</div>

  </body>
</html>

app/views/likes/edit.html.erb
<h1>Likes#edit</h1>
<p>Find me in app/views/likes/edit.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/show.html.erb
<h1>Likes#show</h1>
<p>Find me in app/views/likes/show.html.erb</p>

app/views/pages/home.html.erb
<div class="post-container">

  <% @beets.order('created_at DESC').each do |beet| %>

    <div class="post" id="<%= beet.id %>">

      <pre><%= beet.content %></pre>

      <div class="info">

        <a href="/users/<%= beet.user_id %>" class="info-item"><%= beet.user.username %></a>

        <% if @current_user.present? %>

          <% if @likes.where(user_id: @current_user.id, beet_id: beet.id).any? == true %>

            <%= link_to "♥ #{ @likes.where(beet_id: beet.id).count }", root_path(:user_id => @current_user.id, :beet_id => beet.id), :id => "liked", :method => 'delete' %>

          <% else %>

            <p>
              <%= form_for @like_new do |f| %>
                <%= f.hidden_field :beet_id, value: beet.id %>
                <%= f.hidden_field :user_id, value: @current_user.id %>
                <%= f.submit "♡ #{@likes.where(beet_id: beet.id).count}", :id => "like" %>
              <% end %>
            </p>

          <% end %>

        <% else %>

          <%= link_to "♡ #{@likes.where(beet_id: beet.id).count}", login_path, :id => "like" %>

        <% end %>

        <a href="/beets/<%= beet.id %>" id="comment-beet" class="info-item">comments <%= "[#{@comments.where(beet_id: beet.id).count}]" if @comments.where(beet_id: beet.id).count != 0 %></a>

        <div class="tooltip">
          <%= link_to "", root_path(:id => beet.id), :class => 'far fa-copy', :id => 'clipboard', :method => 'clipboard' %><span class="tooltiptext">Copy to clipboard</span>
        </div>

      </div>

    </div>

  <% end %>

</div>

app/views/session/_form.html.erb
<% if flash[:error].present? %>
  <p class="error">
    <%= flash[:error] %>
  </p>
<% end %>

<%= form_tag login_path do %>
  <%= label_tag :email %>
  <%= email_field_tag :email  %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag "sign in" %>
<% end %>

app/views/session/new.html.erb
<div class="page-container">

  <h1>sign in</h1>

  <%= render :partial => 'form' %>

  <div class="info-container">

    <p>don't have an account? sign up <%= link_to "here", new_user_path %>.</p>
    
  </div>

</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>

  <%= f.label :email %>
  <%= f.email_field :email, :required => true %>

  <%= f.label :username %>
  <%= f.text_field :username, :maxlength => 18, :required => true %>

  <%= f.label :bio %>
  <%= f.text_field :bio %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :required => true %>

  <%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<div class="page-container">

<%= render :partial => 'form'  %>

</div>

app/views/users/index.html.erb
<h1>All Users for testing</h1>

<% @users.each do |user| %>
  <%= link_to user.email, user %>
<% end %>

app/views/users/new.html.erb
<div class="page-container">

  <h1>Create new user</h1>

  <%= render :partial => 'form'  %>

  <div class="info-container">

    <p>already have an account? log in <%= link_to "here", login_path %>.</p>
    
  </div>

</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<div class="controls">

  <% if @current_user.present? && @current_user.id == @user.id %>
    <%= link_to 'edit profile', edit_user_path %>
  <% end %>

  <% if @user.bio.present? %>
    <p><%= @user.bio %></p>
  <% end %>

</div>

<div class="post-container">

  <% @beets.order('created_at DESC').each do |beet| %>

    <% if beet.user_id == @user.id %>

      <div class="post">

        <pre><%= beet.content %></pre>

        <div class="info">

          <a href="/users/<%= beet.user_id %>" class="info-item"><%= beet.user.username %></a>

          <% if @current_user.present? %>

            <% if @likes.where(user_id: @current_user.id, beet_id: beet.id).any? == true %>

              <%= link_to "♥ #{ @likes.where(beet_id: beet.id).count }", root_path(:user_id => @current_user.id, :beet_id => beet.id), :id => "liked", :method => 'delete' %>

            <% else %>

              <p>
                <%= form_for @like_new do |f| %>
                  <%= f.hidden_field :beet_id, value: beet.id %>
                  <%= f.hidden_field :user_id, value: @current_user.id %>
                  <%= f.submit "♡ #{@likes.where(beet_id: beet.id).count}", :id => "like" %>
                <% end %>
              </p>

            <% end %>

          <% else %>

            <%= link_to "♡ #{@likes.where(beet_id: beet.id).count}", login_path, :id => "like" %>

          <% end %>

          <a href="/beets/<%= beet.id %>" id="comment-beet" class="info-item">comments <%= "[#{@comments.where(beet_id: beet.id).count}]" if @comments.where(beet_id: beet.id).count != 0 %></a>

          <div class="tooltip">
            <%= link_to "", root_path(:id => beet.id), :class => 'far fa-copy', :id => 'clipboard', :method => 'clipboard' %><span class="tooltiptext">Copy to clipboard</span>
          </div>

        </div>

      </div>

    <% end %>

  <% end %>

</div>